services:
  product-db:
    image: postgres
    container_name: postgres_container
    restart: on-failure
    env_file:
      - ../.env
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - ../.env
    ports:
      - "5050:80"
    depends_on:
      - product-db
    
  product-api:
    build:
      context: ../services/product-service
      dockerfile: ../../docker/product.dockerfile
    container_name: product_api
    restart: on-failure
    # env_file:
    #   - ../.env
    ports:
      - "8080:8080"
    depends_on:
      - product-db