services:
  product-db:
    image: postgres
    container_name: postgres_container
    restart: on-failure
    env_file:
      - ../.env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - ../.env
    ports:
      - "5050:80"
    depends_on:
      - product-db