name: Build and publish Docker image
description: Build and publish Docker image to registry

inputs:
  context:
    description: "Path to the Docker context directory"
    required: true
  dockerfile_name:
    description: "Name of the Dockerfile"
    required: true
  version:
    description: "Version of the Docker image"
    required: true
  docker_token:
    description: "Docker Hub token"
    required: true
  docker_username:
    description: "Docker Hub username"
    required: true

runs:
  using: "composite"
  steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # username: "${{ inputs.docker_username }}"
          username: zhunism
          password: "${{ inputs.docker_token }}"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "${{ inputs.context }}"
          dockerfile: "./docker/${{ inputs.dockerfile_name }}"
          file: "./docker"
          tags: "zhunism/${{ inputs.context }}:${{ inputs.version }}"