# .github/workflows/detect-changes-all.yaml

name: Detect Service Changes

on:
  workflow_call:
    outputs:
      product_service:
        description: "true if product service has changes"
        value: ${{ jobs.detect-product-service.outputs.is_changes }}
      order_service:
        description: "true if order service has changes"
        value: ${{ jobs.detect-order-service.outputs.is_changes }}
      inventory_service:
        description: "true if inventory service has changes"
        value: ${{ jobs.detect-inventory-service.outputs.is_changes }}

jobs:
  detect-product-service:
    runs-on: ubuntu-latest
    outputs:
      is_changes: ${{ steps.detect.outputs.is_changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/detect-changes
        id: detect
        with:
          service_path: '**/services/product-service/**'
        name: Detect product service changes

  detect-order-service:
    runs-on: ubuntu-latest
    outputs:
      is_changes: ${{ steps.detect.outputs.is_changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/detect-changes
        id: detect
        with:
          service_path: '**/services/order-service/**'
        name: Detect order service changes

  detect-inventory-service:
    runs-on: ubuntu-latest
    outputs:
      is_changes: ${{ steps.detect.outputs.is_changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/detect-changes
        id: detect
        with:
          service_path: '**/services/inventory-service/**'
        name: Detect inventory service changes
