name: Detect Service Changes

on:
  workflow_call:
    outputs:
      product_service:
        description: "true if product service has changes"
        value: ${{ jobs.detect-product-service.outputs.is_changes }}
      order_service:
        description: "true if order service has changes"
        value: ${{ jobs.detect-order-service.outputs.is_changes }}
      inventory_service:
        description: "true if inventory service has changes"
        value: ${{ jobs.detect-inventory-service.outputs.is_changes }}

jobs:
  detect-product-service:
    name: Detect product service changes
    uses: ./.github/workflows/detect-changes.yaml
    with:
      service_path: "**/services/product-service/**"
  detect-order-service:
    name: Detect order service changes
    uses: ./.github/workflows/detect-changes.yaml
    with:
      service_path: "**/services/order-service/**"
  detect-inventory-service:
    name: Detect inventory service changes
    uses: ./.github/workflows/detect-changes.yaml
    with:
      service_path: "**/services/inventory-service/**"
