name: "Production CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  product-service-workflows:
    uses: ./.github/workflows/product-workflows.yaml
    name: Product service
    secrets: inherit
