name: "Production CI"

on:
  push:
    paths-ignore: [ '*.txt' ] # Ignore version.txt changes
    branches:
      - master
      - feat/ci # TODO: remove this branch when the CI is stable

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      product_service: ${{ steps.detected.outputs.product_service }}
      order_service: ${{ steps.detected.outputs.order_service }}
      inventory_service: ${{ steps.detected.outputs.inventory_service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/stages/detect-changes.yaml
        name: Detect services changes
        id: detected

  debug:
    runs-on: ubuntu-latest
    needs: detect-changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug
        run: |
          echo "Product service changes: ${{ needs.detect-changes.outputs.product_service }}"
          echo "Order service changes: ${{ needs.detect-changes.outputs.order_service }}"
          echo "Inventory service changes: ${{ needs.detect-changes.outputs.inventory_service }}"

