
name: Detect Service Changes

on:
  workflow_call:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      is_changes: ${{ steps.detect.outputs.is_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect changes
        id: detect
        uses: ./.github/actions/detect-changes
        with:
          service_path: '**/services/product-service/**'
  
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.read_version.outputs.version }}
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.is_changes == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump application version
        id: read_version
        uses: ./.github/actions/bump-version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish-docker:
    runs-on: ubuntu-latest
    needs: [detect-changes, bump-version]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and publish Docker image
        uses: ./.github/actions/build-and-publish-docker
        with:
          context: './services/product-service'
          dockerfile_name: 'product.dockerfile'
          version: ${{ needs.bump-version.outputs.version }}
          docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }} # TODO: move this out from secrets
          image_name: 'product-service'
  
  # update-version:
  #   runs-on: ubuntu-latest
  #   needs: [extract-version, build-and-publish-docker]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Update version tag
  #       uses: ./.github/actions/update-version
  #       with:
  #         service_path: './services/product-service'
  #         current_version: ${{ needs.extract-version.outputs.version }}
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         ref: ${{ github.ref }}

  