name: "Production CI"

on:
  push:
    paths-ignore: [ '**/services/**/version.txt' ] # Ignore version.txt changes
    branches:
      - master
      - feat/ehc-ci

jobs:
  product-service-workflows:
    uses: ./.github/workflows/product-workflows.yaml
    name: Product service
    secrets: inherit
